# Generated by Django 4.1.5 on 2023-01-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='childcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_original',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products_images/', verbose_name='Главное изображение товара'),
        ),
    ]
